on:
  push:
    branches:
      - main

name: Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up production env variables
        run: cp ~/.env.production $GITHUB_WORKSPACE
      
      - name: Build
        run: |
          cd ~
          docker compose down
          rm -rf ~/front-build/*
          docker compose build
      
      - name: Run
        run: docker compose up -d
      
      - name: Clean-up
        run: docker system prune -f
