on:
  push:
    branches:
      - main

name: Build and Deploy
env:
  VITE_API_URL: /api
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up